name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Triggers whenever you push to main

jobs:
  update-files:
    runs-on: self-hosted  # Directs the job to your Pi
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Downloads the latest code into the runner's work folder
        
      - name: Sync to production folder
        run:
          # The runner downloads files to a temporary '_work' folder. 
          # Use rsync to move them to your actual project directory.
          rsync -avz --exclude '.git' . /home/hopur_3
